### ISSUE TITLE
Tests all use the first instance of the server

### ISSUE THREAD

**Issue by omahlama** [Vokkim/crudivore#2]
The tests always close the port 5000 in express, but all the express routes remain and calling start in server.js again does not overwrite them.

The result is that all the tests use the same, first configuration. I didn't find a good way to fix this, it may require us to rethink how the tests are initiated.

**Comment by Vokkim** [comment]
Fork the Crudivore server into a new process for each test suite:
https://github.com/Vokkim/crudivore/commit/8712a28f6b4c9834fe8958e8c6ab8bd865f2ab68
